/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;
import weightandmass.PlanetaryGravity;

/**
 *
 * @author Nereida Rodríguez Orenes 2ºDAM
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //centrar la ventana en la pantalla
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneBackground = new PanelConFondo("/img/background.gif");
        lbMainTitle = new javax.swing.JLabel();
        lbFormula = new javax.swing.JLabel();
        txtMass = new javax.swing.JTextField();
        lbExplanation = new javax.swing.JLabel();
        lbMass = new javax.swing.JLabel();
        lbkg = new javax.swing.JLabel();
        lbPlanet = new javax.swing.JLabel();
        cbPlanets = new javax.swing.JComboBox<>();
        btnCalculate = new javax.swing.JButton();
        lbWeight = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de peso");

        paneBackground.setBackground(new java.awt.Color(0, 0, 0));

        lbMainTitle.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        lbMainTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbMainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMainTitle.setText("Cálculo de Peso");

        lbFormula.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbFormula.setForeground(new java.awt.Color(255, 255, 255));
        lbFormula.setText("P = m x g");

        txtMass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lbExplanation.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbExplanation.setForeground(new java.awt.Color(255, 255, 255));
        lbExplanation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExplanation.setText("El peso es la masa multiplicada por la gravedad");

        lbMass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbMass.setForeground(new java.awt.Color(255, 255, 255));
        lbMass.setText("Masa:");

        lbkg.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbkg.setForeground(new java.awt.Color(255, 255, 255));
        lbkg.setText("kg");

        lbPlanet.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbPlanet.setForeground(new java.awt.Color(255, 255, 255));
        lbPlanet.setText("Planeta: ");

        cbPlanets.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbPlanets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno" }));

        btnCalculate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCalculate.setText("Calcular");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lbWeight.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbWeight.setForeground(new java.awt.Color(255, 255, 255));
        lbWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paneBackgroundLayout = new javax.swing.GroupLayout(paneBackground);
        paneBackground.setLayout(paneBackgroundLayout);
        paneBackgroundLayout.setHorizontalGroup(
            paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBackgroundLayout.createSequentialGroup()
                        .addComponent(lbFormula)
                        .addGap(400, 400, 400))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBackgroundLayout.createSequentialGroup()
                        .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneBackgroundLayout.createSequentialGroup()
                                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMass, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPlanet))
                                .addGap(44, 44, 44)
                                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMass)
                                    .addComponent(cbPlanets, 0, 156, Short.MAX_VALUE)))
                            .addComponent(lbWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbkg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))))
            .addGroup(paneBackgroundLayout.createSequentialGroup()
                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBackgroundLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(lbMainTitle))
                    .addGroup(paneBackgroundLayout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(btnCalculate)))
                .addContainerGap(266, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbExplanation, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        paneBackgroundLayout.setVerticalGroup(
            paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBackgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lbFormula)
                .addGap(18, 18, 18)
                .addComponent(lbExplanation)
                .addGap(46, 46, 46)
                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMass)
                    .addComponent(lbkg))
                .addGap(18, 18, 18)
                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPlanet)
                    .addComponent(cbPlanets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnCalculate)
                .addGap(37, 37, 37)
                .addComponent(lbWeight)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        //Pasar el texto del Combo Box a mayúsculas y sin tildes (como está en enum)
        String planetName = cbPlanets.getSelectedItem().toString().toUpperCase();
        planetName = planetName.replace("Ú", "U");
         
        try{
            //Recoger valor de la masa
            float mass = Float.parseFloat(txtMass.getText());
             //Cálculo
            PlanetaryGravity planet = PlanetaryGravity.valueOf(planetName);
            float weight = planet.calculateWeight(mass);
            String formatted = String.format("%.2f", weight);
            //Enseñar al usuario
            lbWeight.setText("El peso es: "+formatted+"N");
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Escriba un número", "Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCalculateActionPerformed
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JComboBox<String> cbPlanets;
    private javax.swing.JLabel lbExplanation;
    private javax.swing.JLabel lbFormula;
    private javax.swing.JLabel lbMainTitle;
    private javax.swing.JLabel lbMass;
    private javax.swing.JLabel lbPlanet;
    private javax.swing.JLabel lbWeight;
    private javax.swing.JLabel lbkg;
    private javax.swing.JPanel paneBackground;
    private javax.swing.JTextField txtMass;
    // End of variables declaration//GEN-END:variables
}
